### PR TITLE
fix for 'install python requirements' task for ansible

### PR DESCRIPTION
**Pull request by krzysztofnowak**
@rollcat can you confirm this fix will work? with 'name' it failed to find requirements.txt file

### CODE REVIEW

**Comment by rollcat** [comment]
@krzysztofnowak @maciejzasada is `develop` or `master` the main branch?

This was already fixed on develop: https://github.com/unit9/gae-secure-scaffold-python/pull/1/files

**Comment by krzysztofnowak** [comment]
@rollcat I should create pull request to merge with develop. My fault.  Don't see the option to change it now. I know it was changed on develop branch but
`pip: name=/vagrant/src/requirements.txt`
fails to install on my machine while
`pip: requirements=/vagrant/src/requirements.txt`
works fine. Is it ok for you?

@Rivinek I should ask you too.

**Comment by rollcat** [comment]
> @rollcat I should create pull request to merge with develop. My fault. Don't see the option to change it now.

Calling @maciejzasada to lay the rules out. Personally I believe the `feature/*` -> `develop` -> `master` workflow is broken (for several reasons), and especially on a "boilerplate" / "library" project.

> I know it was changed on develop branch but [...]

OK I see the change.

**Comment by rollcat** [comment]
@krzysztofnowak there are changes on `hotfix/ansible_python_requirements` that are on master and not on develop. Gentlemen, please - the branching model on this project is a total mess.

**Pull request closed without merging**
